imports:
  - {resource: handlers/criteria.yml}
  - {resource: handlers/sortClauses.yml}
  # uncomment this if you see no search results when running command-line scripts
  - {resource: kernel_override.yml}

parameters:
    # Boost functions used to modify relevance scoring
    ezfind_search_engine.search_settings.boost_functions:
        - 'recip(ms(NOW/HOUR,attr_publication_date_dt),4e-12,1000,2)'
    # List of fields to return. Used only when returning raw ezfind data instead of Contents
    ezfind_search_engine.search_settings.fields_to_return:
        - meta_name_t
        - meta_owner_name_t
        - meta_path_string_ms
        - meta_priority_si
        # Score field needs to be renamed as it won't be passed back as-is from eZFind
        - meta_score_value:score

    # The legacy 'fetch function' used to handle searches
    ezfind_search_engine.search_settings.legacy_function_handler.module_name: 'ezfind'
    ezfind_search_engine.search_settings.legacy_function_handler.function_name: 'search'

    ezfind_search_engine.api.service.search.class: Kaliop\EzFindSearchEngineBundle\Core\Repository\SearchService
    ezfind_search_engine.content.criteria_converter.class: Kaliop\EzFindSearchEngineBundle\Core\Persistence\eZFind\Content\Search\Common\Gateway\CriteriaConverter
    ezfind_search_engine.content.sort_clause_converter.class: Kaliop\EzFindSearchEngineBundle\Core\Persistence\eZFind\Content\Search\Common\Gateway\SortClauseConverter

    ezpublish_legacy.kernel.lazy_loader.class: Kaliop\EzFindSearchEngineBundle\Core\MVC\Legacy\Kernel\Loader

services:

    # In order to make sure that the CLI legacy kernel is always booted, we take over the legacy kernel loader,
    # and change the signature of the buildLegacyKernel method
    ezpublish_legacy.kernel.lazy:
        class: Closure
        factory_service: ezpublish_legacy.kernel.lazy_loader
        factory_method: buildLegacyKernel
        arguments:
            - '@ezpublish_legacy.kernel_handler'
            - '@ezpublish_legacy.kernel_handler.cli'

    # Note: tag handler services with 'ezfind_search_engine.content.criterion_handler.filter' to include them in this converter
    ezfind_search_engine.content.criteria_converter.filter:
        class: '%ezfind_search_engine.content.criteria_converter.class%'

    # Note: tag handler services with 'ezfind_search_engine.content.sort_clause_handler' to include them in this converter
    ezfind_search_engine.content.sort_clause_converter:
        class: '%ezfind_search_engine.content.sort_clause_converter.class%'

    ezfind_search_engine.api.service.search:
        class: '%ezfind_search_engine.api.service.search.class%'
        arguments:
            - '@ezpublish_legacy.kernel'
            - '@ezpublish.api.service.content'
            - '@ezpublish.api.service.content_type'
            - '@ezfind_search_engine.content.criteria_converter.filter'
            - '@ezfind_search_engine.content.sort_clause_converter'
            - '%ezfind_search_engine.search_settings.boost_functions%'
            - '%ezfind_search_engine.search_settings.fields_to_return%'
            - true
            - '%ezfind_search_engine.search_settings.legacy_function_handler.module_name%'
            - '%ezfind_search_engine.search_settings.legacy_function_handler.function_name%'
            - '@logger'
        # If you want to have a dedicated log file for this service...
        #tags:
        #    - { name: monolog.logger, channel: ezfind_search_engine }

#############
# OLD STUFF #
#############

#    ezfind_search_engine.service.search_with_facets:
#        class: Kaliop\EzFindSearchEngineBundle\API\Repository\SearchService
#        arguments:
#            - '@ezpublish_legacy.kernel'
#            - '@ezpublish.api.service.content'
#            - '@ezpublish.api.service.content_type'
#            - '@ezfind_search_engine.search.content.criterion_visitor_dispatcher'
#            - '@ezfind_search_engine.search.content.sort_clause_visitor.aggregate'
#            - '@ezfind_search_engine.search.content.facet_builder_visitor.aggregate'
#            - ''
#            - ''
#            - ''
#            - false
#            - @logger
#        calls:
#            - [ setTaxonomyService, [ @ezfind_search_engine.api.service.taxonomy ] ]


#    # Note: services tagged with 'ezfind_search_engine.search.content.criterion_visitor'
#    # are registered to this one using compilation pass
#    ezfind_search_engine.search.content.criterion_visitor_dispatcher:
#        class: Kaliop\EzFindSearchEngineBundle\Persistence\Solr\Content\Search\CriterionVisitorDispatcher
#
#    # Note: services tagged with 'ezfind_search_engine.search.content.sort_clause_visitor'
#    # are registered to this one using compilation pass
#    ezfind_search_engine.search.content.sort_clause_visitor.aggregate:
#        class: Kaliop\EzFindSearchEngineBundle\Persistence\Solr\Content\Search\SortClauseVisitor\Aggregate
#
#    # Note: services tagged with 'ezfind_search_engine.search.content.facet_builder_visitor'
#    # are registered to this one using compilation pass
#    ezfind_search_engine.search.content.facet_builder_visitor.aggregate:
#        class: Kaliop\EzFindSearchEngineBundle\Persistence\Solr\Content\Search\FacetBuilderVisitor\Aggregate
#
#    # Note: services tagged with 'ezfind_search_engine.search.content.query_parameter_visitor'
#    # are registered to this one using compilation pass
#    ezfind_search_engine.search.content.query_parameter_visitor.aggregate:
#        class: Kaliop\EzFindSearchEngineBundle\Persistence\Solr\Content\Search\QueryParameterVisitor\Aggregate
#
#    # Note: services tagged with 'ezfind_search_engine.search.content.query_filter_parameter_visitor'
#    # are registered to this one using compilation pass
#    ezfind_search_engine.search.content.query_filter_parameter_visitor.aggregate:
#        class: Kaliop\EzFindSearchEngineBundle\Persistence\Solr\Content\Search\QueryFilterParameterVisitor\Aggregate
#
#    # Note: services tagged with 'ezfind_search_engine.search.content.applied_filter_visitor'
#    # are registered to this one using compilation pass
#    ezfind_search_engine.search.content.applied_filter_visitor.aggregate:
#        class: Kaliop\EzFindSearchEngineBundle\Persistence\Solr\Content\Search\AppliedFilterVisitor\Aggregate
#
#    # Note: services tagged with 'ezfind_search_engine.search.content.faceted_filter_visitor'
#    # are registered to this one using compilation pass
#    ezfind_search_engine.search.content.faceted_filter_visitor.aggregate:
#        class: Kaliop\EzFindSearchEngineBundle\Persistence\Solr\Content\Search\FacetedFilterVisitor\Aggregate
#
#    ezfind_search_engine.service.search_helper:
#        class: Kaliop\EzFindSearchEngineBundle\API\Repository\SearchHelperService
#        arguments:
#            - ''

#    ezfind_search_engine.form.type.checkbox_hierarchy:
#        class: Kaliop\EzFindSearchEngineBundle\Form\Type\CheckboxHierarchyType
#        tags:
#            - { name: form.type, alias: checkbox_hierarchy }

#    ezfind_search_engine.pagerfanta.view.default:
#        class: Pagerfanta\View\TwitterBootstrap3View
#        public: false
#        tags: [{ name: pagerfanta.view, alias: twitter_bootstrap3 }]
